# Generated by Django 2.0.6 on 2018-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('roll_no', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField()),
                ('branch', models.CharField(blank=True, choices=[('CS', 'Computer Science and Engineering'), ('BME', 'Biomedical Engineering'), ('EC', 'Electronics & Communication Engineering'), ('EEE', 'Electrical Engineering')], max_length=3, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Users',
            },
        ),
    ]
